global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api-service
    metrics_path: /metrics
    static_configs:
      - targets: ["api-service:9101"]
        labels:
          service: api-service

  - job_name: user-service
    metrics_path: /metrics
    static_configs:
      - targets: ["user-service:9102"]
        labels:
          service: user-service

  - job_name: poll-service
    metrics_path: /metrics
    static_configs:
      - targets: ["poll-service:9103"]
        labels:
          service: poll-service

  - job_name: vote-service
    metrics_path: /metrics
    static_configs:
      - targets: ["vote-service:9104"]
        labels:
          service: vote-service

  - job_name: feed-service
    metrics_path: /metrics
    static_configs:
      - targets: ["feed-service:9105"]
        labels:
          service: feed-service

  - job_name: analytics-service
    metrics_path: /metrics
    static_configs:
      - targets: ["analytics-service:9106"]
        labels:
          service: analytics-service
