// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yohnnn/public-survey-platform/back/api/gen/go/poll/v1 (interfaces: PollServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/service/mock/poll_client_mock.go -package=mock github.com/yohnnn/public-survey-platform/back/api/gen/go/poll/v1 PollServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/yohnnn/public-survey-platform/back/api/gen/go/poll/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockPollServiceClient is a mock of PollServiceClient interface.
type MockPollServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPollServiceClientMockRecorder
	isgomock struct{}
}

// MockPollServiceClientMockRecorder is the mock recorder for MockPollServiceClient.
type MockPollServiceClientMockRecorder struct {
	mock *MockPollServiceClient
}

// NewMockPollServiceClient creates a new mock instance.
func NewMockPollServiceClient(ctrl *gomock.Controller) *MockPollServiceClient {
	mock := &MockPollServiceClient{ctrl: ctrl}
	mock.recorder = &MockPollServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollServiceClient) EXPECT() *MockPollServiceClientMockRecorder {
	return m.recorder
}

// CreatePoll mocks base method.
func (m *MockPollServiceClient) CreatePoll(ctx context.Context, in *v1.CreatePollRequest, opts ...grpc.CallOption) (*v1.CreatePollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreatePoll", varargs...)
	ret0, _ := ret[0].(*v1.CreatePollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePoll indicates an expected call of CreatePoll.
func (mr *MockPollServiceClientMockRecorder) CreatePoll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePoll", reflect.TypeOf((*MockPollServiceClient)(nil).CreatePoll), varargs...)
}

// CreateTag mocks base method.
func (m *MockPollServiceClient) CreateTag(ctx context.Context, in *v1.CreateTagRequest, opts ...grpc.CallOption) (*v1.CreateTagResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTag", varargs...)
	ret0, _ := ret[0].(*v1.CreateTagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockPollServiceClientMockRecorder) CreateTag(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockPollServiceClient)(nil).CreateTag), varargs...)
}

// DeletePoll mocks base method.
func (m *MockPollServiceClient) DeletePoll(ctx context.Context, in *v1.DeletePollRequest, opts ...grpc.CallOption) (*v1.DeletePollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeletePoll", varargs...)
	ret0, _ := ret[0].(*v1.DeletePollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePoll indicates an expected call of DeletePoll.
func (mr *MockPollServiceClientMockRecorder) DeletePoll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePoll", reflect.TypeOf((*MockPollServiceClient)(nil).DeletePoll), varargs...)
}

// GetPoll mocks base method.
func (m *MockPollServiceClient) GetPoll(ctx context.Context, in *v1.GetPollRequest, opts ...grpc.CallOption) (*v1.GetPollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPoll", varargs...)
	ret0, _ := ret[0].(*v1.GetPollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoll indicates an expected call of GetPoll.
func (mr *MockPollServiceClientMockRecorder) GetPoll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoll", reflect.TypeOf((*MockPollServiceClient)(nil).GetPoll), varargs...)
}

// ListPolls mocks base method.
func (m *MockPollServiceClient) ListPolls(ctx context.Context, in *v1.ListPollsRequest, opts ...grpc.CallOption) (*v1.ListPollsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPolls", varargs...)
	ret0, _ := ret[0].(*v1.ListPollsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolls indicates an expected call of ListPolls.
func (mr *MockPollServiceClientMockRecorder) ListPolls(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolls", reflect.TypeOf((*MockPollServiceClient)(nil).ListPolls), varargs...)
}

// ListTags mocks base method.
func (m *MockPollServiceClient) ListTags(ctx context.Context, in *v1.ListTagsRequest, opts ...grpc.CallOption) (*v1.ListTagsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTags", varargs...)
	ret0, _ := ret[0].(*v1.ListTagsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockPollServiceClientMockRecorder) ListTags(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockPollServiceClient)(nil).ListTags), varargs...)
}

// UpdatePoll mocks base method.
func (m *MockPollServiceClient) UpdatePoll(ctx context.Context, in *v1.UpdatePollRequest, opts ...grpc.CallOption) (*v1.UpdatePollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdatePoll", varargs...)
	ret0, _ := ret[0].(*v1.UpdatePollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePoll indicates an expected call of UpdatePoll.
func (mr *MockPollServiceClientMockRecorder) UpdatePoll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePoll", reflect.TypeOf((*MockPollServiceClient)(nil).UpdatePoll), varargs...)
}
