// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/service/mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	outbox "github.com/yohnnn/public-survey-platform/back/pkg/outbox"
	gomock "go.uber.org/mock/gomock"
)

// MockVoteRepository is a mock of VoteRepository interface.
type MockVoteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVoteRepositoryMockRecorder
	isgomock struct{}
}

// MockVoteRepositoryMockRecorder is the mock recorder for MockVoteRepository.
type MockVoteRepositoryMockRecorder struct {
	mock *MockVoteRepository
}

// NewMockVoteRepository creates a new mock instance.
func NewMockVoteRepository(ctrl *gomock.Controller) *MockVoteRepository {
	mock := &MockVoteRepository{ctrl: ctrl}
	mock.recorder = &MockVoteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVoteRepository) EXPECT() *MockVoteRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserVote mocks base method.
func (m *MockVoteRepository) DeleteUserVote(ctx context.Context, userID, pollID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserVote", ctx, userID, pollID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserVote indicates an expected call of DeleteUserVote.
func (mr *MockVoteRepositoryMockRecorder) DeleteUserVote(ctx, userID, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserVote", reflect.TypeOf((*MockVoteRepository)(nil).DeleteUserVote), ctx, userID, pollID)
}

// GetUserVote mocks base method.
func (m *MockVoteRepository) GetUserVote(ctx context.Context, userID, pollID string) ([]string, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserVote", ctx, userID, pollID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserVote indicates an expected call of GetUserVote.
func (mr *MockVoteRepositoryMockRecorder) GetUserVote(ctx, userID, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserVote", reflect.TypeOf((*MockVoteRepository)(nil).GetUserVote), ctx, userID, pollID)
}

// ReplaceUserVote mocks base method.
func (m *MockVoteRepository) ReplaceUserVote(ctx context.Context, userID, pollID string, optionIDs []string, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceUserVote", ctx, userID, pollID, optionIDs, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceUserVote indicates an expected call of ReplaceUserVote.
func (mr *MockVoteRepositoryMockRecorder) ReplaceUserVote(ctx, userID, pollID, optionIDs, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceUserVote", reflect.TypeOf((*MockVoteRepository)(nil).ReplaceUserVote), ctx, userID, pollID, optionIDs, createdAt)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOutboxRepository) Add(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockOutboxRepositoryMockRecorder) Add(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOutboxRepository)(nil).Add), ctx, event)
}

// ListUnpublished mocks base method.
func (m *MockOutboxRepository) ListUnpublished(ctx context.Context, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockOutboxRepositoryMockRecorder) ListUnpublished(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockOutboxRepository)(nil).ListUnpublished), ctx, limit)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, eventID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, eventID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, eventID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, eventID, reason)
}

// MarkPublished mocks base method.
func (m *MockOutboxRepository) MarkPublished(ctx context.Context, eventID string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, eventID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkPublished(ctx, eventID, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkPublished), ctx, eventID, publishedAt)
}
