// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/service/mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	outbox "github.com/yohnnn/public-survey-platform/back/pkg/outbox"
	models "github.com/yohnnn/public-survey-platform/back/services/poll-service/internal/models"
	repository "github.com/yohnnn/public-survey-platform/back/services/poll-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockPollRepository is a mock of PollRepository interface.
type MockPollRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPollRepositoryMockRecorder
	isgomock struct{}
}

// MockPollRepositoryMockRecorder is the mock recorder for MockPollRepository.
type MockPollRepositoryMockRecorder struct {
	mock *MockPollRepository
}

// NewMockPollRepository creates a new mock instance.
func NewMockPollRepository(ctrl *gomock.Controller) *MockPollRepository {
	mock := &MockPollRepository{ctrl: ctrl}
	mock.recorder = &MockPollRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollRepository) EXPECT() *MockPollRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPollRepository) Create(ctx context.Context, poll models.Poll, options []models.PollOption, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, poll, options, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPollRepositoryMockRecorder) Create(ctx, poll, options, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPollRepository)(nil).Create), ctx, poll, options, tagIDs)
}

// DeleteByIDAndCreator mocks base method.
func (m *MockPollRepository) DeleteByIDAndCreator(ctx context.Context, pollID, creatorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByIDAndCreator", ctx, pollID, creatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByIDAndCreator indicates an expected call of DeleteByIDAndCreator.
func (mr *MockPollRepositoryMockRecorder) DeleteByIDAndCreator(ctx, pollID, creatorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByIDAndCreator", reflect.TypeOf((*MockPollRepository)(nil).DeleteByIDAndCreator), ctx, pollID, creatorID)
}

// GetByID mocks base method.
func (m *MockPollRepository) GetByID(ctx context.Context, id string) (models.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPollRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPollRepository)(nil).GetByID), ctx, id)
}

// GetOptionsByPollIDs mocks base method.
func (m *MockPollRepository) GetOptionsByPollIDs(ctx context.Context, pollIDs []string) (map[string][]models.PollOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionsByPollIDs", ctx, pollIDs)
	ret0, _ := ret[0].(map[string][]models.PollOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionsByPollIDs indicates an expected call of GetOptionsByPollIDs.
func (mr *MockPollRepositoryMockRecorder) GetOptionsByPollIDs(ctx, pollIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionsByPollIDs", reflect.TypeOf((*MockPollRepository)(nil).GetOptionsByPollIDs), ctx, pollIDs)
}

// GetTagsByPollIDs mocks base method.
func (m *MockPollRepository) GetTagsByPollIDs(ctx context.Context, pollIDs []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByPollIDs", ctx, pollIDs)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByPollIDs indicates an expected call of GetTagsByPollIDs.
func (mr *MockPollRepositoryMockRecorder) GetTagsByPollIDs(ctx, pollIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByPollIDs", reflect.TypeOf((*MockPollRepository)(nil).GetTagsByPollIDs), ctx, pollIDs)
}

// IncrementOptionVotes mocks base method.
func (m *MockPollRepository) IncrementOptionVotes(ctx context.Context, pollID, optionID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOptionVotes", ctx, pollID, optionID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOptionVotes indicates an expected call of IncrementOptionVotes.
func (mr *MockPollRepositoryMockRecorder) IncrementOptionVotes(ctx, pollID, optionID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOptionVotes", reflect.TypeOf((*MockPollRepository)(nil).IncrementOptionVotes), ctx, pollID, optionID, delta)
}

// List mocks base method.
func (m *MockPollRepository) List(ctx context.Context, filter repository.PollListFilter) ([]models.Poll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]models.Poll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPollRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPollRepository)(nil).List), ctx, filter)
}

// MarkEventProcessed mocks base method.
func (m *MockPollRepository) MarkEventProcessed(ctx context.Context, eventID, topic string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, eventID, topic)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockPollRepositoryMockRecorder) MarkEventProcessed(ctx, eventID, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockPollRepository)(nil).MarkEventProcessed), ctx, eventID, topic)
}

// ReplaceTags mocks base method.
func (m *MockPollRepository) ReplaceTags(ctx context.Context, pollID string, tagIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTags", ctx, pollID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceTags indicates an expected call of ReplaceTags.
func (mr *MockPollRepositoryMockRecorder) ReplaceTags(ctx, pollID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTags", reflect.TypeOf((*MockPollRepository)(nil).ReplaceTags), ctx, pollID, tagIDs)
}

// UpdateByIDAndCreator mocks base method.
func (m *MockPollRepository) UpdateByIDAndCreator(ctx context.Context, pollID, creatorID string, patch repository.PollPatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByIDAndCreator", ctx, pollID, creatorID, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByIDAndCreator indicates an expected call of UpdateByIDAndCreator.
func (mr *MockPollRepositoryMockRecorder) UpdateByIDAndCreator(ctx, pollID, creatorID, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByIDAndCreator", reflect.TypeOf((*MockPollRepository)(nil).UpdateByIDAndCreator), ctx, pollID, creatorID, patch)
}

// UpdateTotalVotes mocks base method.
func (m *MockPollRepository) UpdateTotalVotes(ctx context.Context, pollID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTotalVotes", ctx, pollID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTotalVotes indicates an expected call of UpdateTotalVotes.
func (mr *MockPollRepositoryMockRecorder) UpdateTotalVotes(ctx, pollID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTotalVotes", reflect.TypeOf((*MockPollRepository)(nil).UpdateTotalVotes), ctx, pollID, delta)
}

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagRepository) Create(ctx context.Context, tag models.Tag) (models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tag)
	ret0, _ := ret[0].(models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagRepositoryMockRecorder) Create(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagRepository)(nil).Create), ctx, tag)
}

// EnsureByNames mocks base method.
func (m *MockTagRepository) EnsureByNames(ctx context.Context, names []string) ([]models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureByNames", ctx, names)
	ret0, _ := ret[0].([]models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureByNames indicates an expected call of EnsureByNames.
func (mr *MockTagRepositoryMockRecorder) EnsureByNames(ctx, names any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureByNames", reflect.TypeOf((*MockTagRepository)(nil).EnsureByNames), ctx, names)
}

// List mocks base method.
func (m *MockTagRepository) List(ctx context.Context) ([]models.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]models.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagRepository)(nil).List), ctx)
}

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockOutboxRepository) Add(ctx context.Context, event outbox.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockOutboxRepositoryMockRecorder) Add(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockOutboxRepository)(nil).Add), ctx, event)
}

// ListUnpublished mocks base method.
func (m *MockOutboxRepository) ListUnpublished(ctx context.Context, limit int) ([]outbox.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnpublished", ctx, limit)
	ret0, _ := ret[0].([]outbox.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnpublished indicates an expected call of ListUnpublished.
func (mr *MockOutboxRepositoryMockRecorder) ListUnpublished(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnpublished", reflect.TypeOf((*MockOutboxRepository)(nil).ListUnpublished), ctx, limit)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, eventID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, eventID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, eventID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, eventID, reason)
}

// MarkPublished mocks base method.
func (m *MockOutboxRepository) MarkPublished(ctx context.Context, eventID string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, eventID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkPublished(ctx, eventID, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkPublished), ctx, eventID, publishedAt)
}
