// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/service/mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/yohnnn/public-survey-platform/back/services/analytics-service/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// GetAgeStats mocks base method.
func (m *MockAnalyticsRepository) GetAgeStats(ctx context.Context, pollID string) ([]models.AgeStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgeStats", ctx, pollID)
	ret0, _ := ret[0].([]models.AgeStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgeStats indicates an expected call of GetAgeStats.
func (mr *MockAnalyticsRepositoryMockRecorder) GetAgeStats(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgeStats", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetAgeStats), ctx, pollID)
}

// GetCountryStats mocks base method.
func (m *MockAnalyticsRepository) GetCountryStats(ctx context.Context, pollID string) ([]models.CountryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountryStats", ctx, pollID)
	ret0, _ := ret[0].([]models.CountryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountryStats indicates an expected call of GetCountryStats.
func (mr *MockAnalyticsRepositoryMockRecorder) GetCountryStats(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountryStats", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetCountryStats), ctx, pollID)
}

// GetGenderStats mocks base method.
func (m *MockAnalyticsRepository) GetGenderStats(ctx context.Context, pollID string) ([]models.GenderStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenderStats", ctx, pollID)
	ret0, _ := ret[0].([]models.GenderStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenderStats indicates an expected call of GetGenderStats.
func (mr *MockAnalyticsRepositoryMockRecorder) GetGenderStats(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenderStats", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetGenderStats), ctx, pollID)
}

// GetPollAnalytics mocks base method.
func (m *MockAnalyticsRepository) GetPollAnalytics(ctx context.Context, pollID string) (models.PollAnalytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPollAnalytics", ctx, pollID)
	ret0, _ := ret[0].(models.PollAnalytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPollAnalytics indicates an expected call of GetPollAnalytics.
func (mr *MockAnalyticsRepositoryMockRecorder) GetPollAnalytics(ctx, pollID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPollAnalytics", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetPollAnalytics), ctx, pollID)
}

// IncrementAgeVotes mocks base method.
func (m *MockAnalyticsRepository) IncrementAgeVotes(ctx context.Context, pollID, ageRange string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementAgeVotes", ctx, pollID, ageRange, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementAgeVotes indicates an expected call of IncrementAgeVotes.
func (mr *MockAnalyticsRepositoryMockRecorder) IncrementAgeVotes(ctx, pollID, ageRange, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementAgeVotes", reflect.TypeOf((*MockAnalyticsRepository)(nil).IncrementAgeVotes), ctx, pollID, ageRange, delta)
}

// IncrementCountryVotes mocks base method.
func (m *MockAnalyticsRepository) IncrementCountryVotes(ctx context.Context, pollID, country string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementCountryVotes", ctx, pollID, country, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementCountryVotes indicates an expected call of IncrementCountryVotes.
func (mr *MockAnalyticsRepositoryMockRecorder) IncrementCountryVotes(ctx, pollID, country, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementCountryVotes", reflect.TypeOf((*MockAnalyticsRepository)(nil).IncrementCountryVotes), ctx, pollID, country, delta)
}

// IncrementGenderVotes mocks base method.
func (m *MockAnalyticsRepository) IncrementGenderVotes(ctx context.Context, pollID, gender string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementGenderVotes", ctx, pollID, gender, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementGenderVotes indicates an expected call of IncrementGenderVotes.
func (mr *MockAnalyticsRepositoryMockRecorder) IncrementGenderVotes(ctx, pollID, gender, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementGenderVotes", reflect.TypeOf((*MockAnalyticsRepository)(nil).IncrementGenderVotes), ctx, pollID, gender, delta)
}

// IncrementOptionVotes mocks base method.
func (m *MockAnalyticsRepository) IncrementOptionVotes(ctx context.Context, pollID, optionID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOptionVotes", ctx, pollID, optionID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOptionVotes indicates an expected call of IncrementOptionVotes.
func (mr *MockAnalyticsRepositoryMockRecorder) IncrementOptionVotes(ctx, pollID, optionID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOptionVotes", reflect.TypeOf((*MockAnalyticsRepository)(nil).IncrementOptionVotes), ctx, pollID, optionID, delta)
}

// MarkEventProcessed mocks base method.
func (m *MockAnalyticsRepository) MarkEventProcessed(ctx context.Context, eventID, topic string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, eventID, topic)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockAnalyticsRepositoryMockRecorder) MarkEventProcessed(ctx, eventID, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockAnalyticsRepository)(nil).MarkEventProcessed), ctx, eventID, topic)
}
