// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interfaces.go -destination=internal/service/mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/yohnnn/public-survey-platform/back/services/feed-service/internal/models"
	repository "github.com/yohnnn/public-survey-platform/back/services/feed-service/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedRepository is a mock of FeedRepository interface.
type MockFeedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedRepositoryMockRecorder is the mock recorder for MockFeedRepository.
type MockFeedRepositoryMockRecorder struct {
	mock *MockFeedRepository
}

// NewMockFeedRepository creates a new mock instance.
func NewMockFeedRepository(ctrl *gomock.Controller) *MockFeedRepository {
	mock := &MockFeedRepository{ctrl: ctrl}
	mock.recorder = &MockFeedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedRepository) EXPECT() *MockFeedRepositoryMockRecorder {
	return m.recorder
}

// AddPendingOptionVotes mocks base method.
func (m *MockFeedRepository) AddPendingOptionVotes(ctx context.Context, pollID, optionID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPendingOptionVotes", ctx, pollID, optionID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPendingOptionVotes indicates an expected call of AddPendingOptionVotes.
func (mr *MockFeedRepositoryMockRecorder) AddPendingOptionVotes(ctx, pollID, optionID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPendingOptionVotes", reflect.TypeOf((*MockFeedRepository)(nil).AddPendingOptionVotes), ctx, pollID, optionID, delta)
}

// AddPendingTotalVotes mocks base method.
func (m *MockFeedRepository) AddPendingTotalVotes(ctx context.Context, pollID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPendingTotalVotes", ctx, pollID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPendingTotalVotes indicates an expected call of AddPendingTotalVotes.
func (mr *MockFeedRepositoryMockRecorder) AddPendingTotalVotes(ctx, pollID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPendingTotalVotes", reflect.TypeOf((*MockFeedRepository)(nil).AddPendingTotalVotes), ctx, pollID, delta)
}

// ApplyPendingVotes mocks base method.
func (m *MockFeedRepository) ApplyPendingVotes(ctx context.Context, feedItemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPendingVotes", ctx, feedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPendingVotes indicates an expected call of ApplyPendingVotes.
func (mr *MockFeedRepositoryMockRecorder) ApplyPendingVotes(ctx, feedItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPendingVotes", reflect.TypeOf((*MockFeedRepository)(nil).ApplyPendingVotes), ctx, feedItemID)
}

// CreateFeedItem mocks base method.
func (m *MockFeedRepository) CreateFeedItem(ctx context.Context, item models.FeedItem, options []models.FeedItemOption, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeedItem", ctx, item, options, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFeedItem indicates an expected call of CreateFeedItem.
func (mr *MockFeedRepositoryMockRecorder) CreateFeedItem(ctx, item, options, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeedItem", reflect.TypeOf((*MockFeedRepository)(nil).CreateFeedItem), ctx, item, options, tags)
}

// DeleteFeedItem mocks base method.
func (m *MockFeedRepository) DeleteFeedItem(ctx context.Context, feedItemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedItem", ctx, feedItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeedItem indicates an expected call of DeleteFeedItem.
func (mr *MockFeedRepositoryMockRecorder) DeleteFeedItem(ctx, feedItemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedItem", reflect.TypeOf((*MockFeedRepository)(nil).DeleteFeedItem), ctx, feedItemID)
}

// GetFeed mocks base method.
func (m *MockFeedRepository) GetFeed(ctx context.Context, filter repository.FeedListFilter) ([]models.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeed", ctx, filter)
	ret0, _ := ret[0].([]models.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeed indicates an expected call of GetFeed.
func (mr *MockFeedRepositoryMockRecorder) GetFeed(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeed", reflect.TypeOf((*MockFeedRepository)(nil).GetFeed), ctx, filter)
}

// GetFollowingFeed mocks base method.
func (m *MockFeedRepository) GetFollowingFeed(ctx context.Context, filter repository.FeedListFilter) ([]models.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingFeed", ctx, filter)
	ret0, _ := ret[0].([]models.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingFeed indicates an expected call of GetFollowingFeed.
func (mr *MockFeedRepositoryMockRecorder) GetFollowingFeed(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingFeed", reflect.TypeOf((*MockFeedRepository)(nil).GetFollowingFeed), ctx, filter)
}

// GetOptionsByFeedItemIDs mocks base method.
func (m *MockFeedRepository) GetOptionsByFeedItemIDs(ctx context.Context, feedItemIDs []string) (map[string][]models.FeedItemOption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptionsByFeedItemIDs", ctx, feedItemIDs)
	ret0, _ := ret[0].(map[string][]models.FeedItemOption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptionsByFeedItemIDs indicates an expected call of GetOptionsByFeedItemIDs.
func (mr *MockFeedRepositoryMockRecorder) GetOptionsByFeedItemIDs(ctx, feedItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptionsByFeedItemIDs", reflect.TypeOf((*MockFeedRepository)(nil).GetOptionsByFeedItemIDs), ctx, feedItemIDs)
}

// GetTagsByFeedItemIDs mocks base method.
func (m *MockFeedRepository) GetTagsByFeedItemIDs(ctx context.Context, feedItemIDs []string) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByFeedItemIDs", ctx, feedItemIDs)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByFeedItemIDs indicates an expected call of GetTagsByFeedItemIDs.
func (mr *MockFeedRepositoryMockRecorder) GetTagsByFeedItemIDs(ctx, feedItemIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByFeedItemIDs", reflect.TypeOf((*MockFeedRepository)(nil).GetTagsByFeedItemIDs), ctx, feedItemIDs)
}

// GetTrending mocks base method.
func (m *MockFeedRepository) GetTrending(ctx context.Context, filter repository.FeedListFilter) ([]models.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrending", ctx, filter)
	ret0, _ := ret[0].([]models.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrending indicates an expected call of GetTrending.
func (mr *MockFeedRepositoryMockRecorder) GetTrending(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrending", reflect.TypeOf((*MockFeedRepository)(nil).GetTrending), ctx, filter)
}

// GetUserPolls mocks base method.
func (m *MockFeedRepository) GetUserPolls(ctx context.Context, filter repository.FeedListFilter) ([]models.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPolls", ctx, filter)
	ret0, _ := ret[0].([]models.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPolls indicates an expected call of GetUserPolls.
func (mr *MockFeedRepositoryMockRecorder) GetUserPolls(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPolls", reflect.TypeOf((*MockFeedRepository)(nil).GetUserPolls), ctx, filter)
}

// IncrementOptionVotes mocks base method.
func (m *MockFeedRepository) IncrementOptionVotes(ctx context.Context, optionID string, delta int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOptionVotes", ctx, optionID, delta)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementOptionVotes indicates an expected call of IncrementOptionVotes.
func (mr *MockFeedRepositoryMockRecorder) IncrementOptionVotes(ctx, optionID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOptionVotes", reflect.TypeOf((*MockFeedRepository)(nil).IncrementOptionVotes), ctx, optionID, delta)
}

// MarkEventProcessed mocks base method.
func (m *MockFeedRepository) MarkEventProcessed(ctx context.Context, eventID, topic string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, eventID, topic)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockFeedRepositoryMockRecorder) MarkEventProcessed(ctx, eventID, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockFeedRepository)(nil).MarkEventProcessed), ctx, eventID, topic)
}

// UpdateFeedItem mocks base method.
func (m *MockFeedRepository) UpdateFeedItem(ctx context.Context, item models.FeedItem, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFeedItem", ctx, item, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFeedItem indicates an expected call of UpdateFeedItem.
func (mr *MockFeedRepositoryMockRecorder) UpdateFeedItem(ctx, item, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFeedItem", reflect.TypeOf((*MockFeedRepository)(nil).UpdateFeedItem), ctx, item, tags)
}

// UpdateTotalVotes mocks base method.
func (m *MockFeedRepository) UpdateTotalVotes(ctx context.Context, feedItemID string, delta int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTotalVotes", ctx, feedItemID, delta)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTotalVotes indicates an expected call of UpdateTotalVotes.
func (mr *MockFeedRepositoryMockRecorder) UpdateTotalVotes(ctx, feedItemID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTotalVotes", reflect.TypeOf((*MockFeedRepository)(nil).UpdateTotalVotes), ctx, feedItemID, delta)
}
